leiosNotifyMessage
     = msgLeiosNotificationRequestNext
     / msgLeiosBlockAnnouncement
     / msgLeiosBlockOffer
     / msgLeiosBlockTxsOffer
     / msgLeiosVotes
     / msgClientDone

msgLeiosNotificationRequestNext = [0]
msgLeiosBlockAnnouncement       = [1, announcement]
msgLeiosBlockOffer              = [2, point, eb_size]
msgLeiosBlockTxsOffer           = [3, point]
msgLeiosVotes                   = [4, [1* vote]]
msgClientDone                   = [5]

announcement = any ; TODO
point = (slot, eb_hash)
eb_size = base.word32 ; TODO should not be needed, because announcement
slot = base.slotno
eb_hash = base.hash

vote =
  [ slot
  , eb_hash
  , voter_id              : base.word16
  , vote_signature        : leios_bls_signature
  ]

; FIXME: non-mocked signatures
;leios_bls_signature = bytes .size 48
leios_bls_signature = bool

;# import base as base
