leiosNotifyMessage
     = msgLeiosNotificationRequestNext
     / msgLeiosBlockAnnouncement
     / msgLeiosBlockOffer
     / msgLeiosBlockTxsOffer
     / msgLeiosVotesOffer
     / msgClientDone

msgLeiosNotificationRequestNext = [0]
msgLeiosBlockAnnouncement       = [1, announcement_header]
msgLeiosBlockOffer              = [2, point]
msgLeiosBlockTxsOffer           = [3, point]
msgLeiosVotes                   = [4, [1* vote]]
msgClientDone                   = [5]

announcement_header = any ; TODO
point = (slot, eb_hash)
slot = base.slotNo
eb_hash = base.hash

vote =
  [ election_id           : base.slotNo
  , voter_id              : base.word16
  , eb_hash
  , vote_signature        : leios_bls_signature
  ]

leios_bls_signature = bytes .size 48


;# import base as base
