leiosNotifyMessage
     = msgLeiosNotificationRequestNext
     / msgLeiosBlockAnnouncement
     / msgLeiosBlockOffer
     / msgLeiosBlockTxsOffer
     / msgClientDone

msgLeiosNotificationRequestNext = [0]
msgLeiosBlockAnnouncement = [1, announcement]
msgLeiosBlockOffer = [2, leios.point, size]
msgLeiosBlockTxsOffer = [3, leios.point]
msgClientDone = [4]

announcement = any ; TODO
size = base.word32

;# import base as base
;# import leios as leios
