leiosBlockFetchMessage
     = msgLeiosBlockRequest
     / msgLeiosBlock
     / msgLeiosBlockTxsRequest
     / msgLeiosBlockTxs
     / msgClientDone
; TODO not implemented yet in leios-prototype
;     / msgLeiosBlockRangeRequest
;     / msgLeiosNextBlockAndTxsInRange
;     / msgLeiosLastBlockAndTxsInRange

msgLeiosBlockRequest           = [0, point]
msgLeiosBlock                  = [1, endorser_block]
msgLeiosBlockTxsRequest        = [2, point, bitmaps]
msgLeiosBlockTxs               = [3, point, bitmaps, tx_list]
; TODO not implemented yet in leios-prototype
; msgLeiosBlockRangeRequest =
;   [ 6
;   , start_slot  : base.slotno
;   , end_slot    : base.slotno
;   , start_hash  : base.hash
;   , end_hash    : base.hash
;   ]
; msgLeiosNextBlockAndTxsInRange = [7, endorser_block, tx_list]
; msgLeiosLastBlockAndTxsInRange = [8, endorser_block, tx_list]
msgClientDone                  = [9]

point = (slot, eb_hash)
slot = base.slotno
eb_hash = base.hash

; map from tx hash to serialized tx byte size
; TODO: add valdity indices analogous to Dijkstra block body
endorser_block = { * base.hash => base.word32 }

; indefinite-length map from 64-tx window index to 64-bit presence bitmap
bitmaps = { * base.word16 => base.word64 }

tx_list = [ *tx.tx ] ; REVIEW: only length-definite?

;# import base as base
;# import tx as tx
